### ISSUE TITLE
Socketed Gems Deal 30% More Elemental Damage is Nested Under The Wrong Heading

### ISSUE THREAD

**Issue by melink14** [poeaffix/poeaffix.github.io#9]
The essence mod 'Socketed Gems Deal 30% More Elemental Damage' is nested underneath the unrelated mod 'Socketed Gems Gain %# Physical Damage As Extra Lightening Damage'.

Found on AR Helmet list (http://poeaffix.net/hm-ar.html#/) but it's on others as well.

![image](https://user-images.githubusercontent.com/1176550/52167790-8b643300-26d5-11e9-9242-be2fca8cfdaa.png)

**Comment by ImaginaryDevelopment** [comment]
should be addressed now
